# Makefile - Educational DES implementation in C.
#
# Targets:
#   make            Builds every binary (default).
#   make test       Builds and runs both test suites.
#   make examples   Builds and runs the demo program.
#   make benchmark  Builds and runs the brute-force benchmark.
#   make clean      Removes all generated artifacts.
#
# Everything generated lives under build/ (benchmark CSVs go to results/),
# so `make clean` never touches source files.

BUILD_DIR  := build
OBJ_DIR    := $(BUILD_DIR)/obj
BIN_DIR    := $(BUILD_DIR)/bin
ATTACK_DIR := benchmark_bruteForce
RESULT_DIR := results

CC       ?= cc
CFLAGS   ?= -std=c11 -O2 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-prototypes
CPPFLAGS += -Iinclude -I$(ATTACK_DIR) -MMD -MP
LDFLAGS  ?=

# Only the attack binaries need threads; the cipher stays dependency-free.
PTHREAD := -pthread

# Core algorithm sources, listed explicitly rather than with a wildcard so a
# stray file in src/ can't silently join the build.
LIB_SRCS := \
	src/des_tables.c \
	src/des_keyschedule.c \
	src/des_feistel.c \
	src/des.c \
	src/des_api.c \
	src/des_modes.c

TEST_SRCS    := tests/test_des.c
EXAMPLE_SRCS := examples/main.c

# Part I experiments whose output goes into the lab report.
EXPERIMENT_SRCS := experiments/modes_experiments.c

# Experiment code for Lab 2 part II: the key space and the searches that
# sweep it. Kept out of LIB_SRCS so the library itself never depends on it.
ATTACK_SRCS := \
	$(ATTACK_DIR)/des_keyspace.c \
	$(ATTACK_DIR)/des_brute_force.c

BENCH_SRCS      := $(ATTACK_DIR)/benchmark.c
ATTACK_TEST_SRCS := $(ATTACK_DIR)/test_bruteforce.c

LIB_OBJS         := $(LIB_SRCS:%.c=$(OBJ_DIR)/%.o)
TEST_OBJS        := $(TEST_SRCS:%.c=$(OBJ_DIR)/%.o)
EXAMPLE_OBJS     := $(EXAMPLE_SRCS:%.c=$(OBJ_DIR)/%.o)
EXPERIMENT_OBJS  := $(EXPERIMENT_SRCS:%.c=$(OBJ_DIR)/%.o)
ATTACK_OBJS      := $(ATTACK_SRCS:%.c=$(OBJ_DIR)/%.o)
BENCH_OBJS       := $(BENCH_SRCS:%.c=$(OBJ_DIR)/%.o)
ATTACK_TEST_OBJS := $(ATTACK_TEST_SRCS:%.c=$(OBJ_DIR)/%.o)

TEST_BIN        := $(BIN_DIR)/test_des
EXAMPLE_BIN     := $(BIN_DIR)/des_demo
EXPERIMENT_BIN  := $(BIN_DIR)/modes_experiments
BENCH_BIN       := $(BIN_DIR)/benchmark_bruteforce
ATTACK_TEST_BIN := $(BIN_DIR)/test_bruteforce

# .d files generated by -MMD: they make a header change force recompilation
# of every .c that includes it.
DEPS := $(LIB_OBJS:.o=.d) $(TEST_OBJS:.o=.d) $(EXAMPLE_OBJS:.o=.d) \
        $(EXPERIMENT_OBJS:.o=.d) $(ATTACK_OBJS:.o=.d) $(BENCH_OBJS:.o=.d) \
        $(ATTACK_TEST_OBJS:.o=.d)

.PHONY: all test examples experiments benchmark clean help

all: $(TEST_BIN) $(ATTACK_TEST_BIN) $(EXAMPLE_BIN) $(EXPERIMENT_BIN) $(BENCH_BIN)

$(TEST_BIN): $(LIB_OBJS) $(TEST_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(EXAMPLE_BIN): $(LIB_OBJS) $(EXAMPLE_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(EXPERIMENT_BIN): $(LIB_OBJS) $(EXPERIMENT_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(BENCH_BIN): $(LIB_OBJS) $(ATTACK_OBJS) $(BENCH_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $(PTHREAD) $^ -o $@ $(LDFLAGS)

$(ATTACK_TEST_BIN): $(LIB_OBJS) $(ATTACK_OBJS) $(ATTACK_TEST_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $(PTHREAD) $^ -o $@ $(LDFLAGS)

$(OBJ_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

test: $(TEST_BIN) $(ATTACK_TEST_BIN)
	@./$(TEST_BIN)
	@./$(ATTACK_TEST_BIN)

examples: $(EXAMPLE_BIN)
	@./$(EXAMPLE_BIN)

experiments: $(EXPERIMENT_BIN)
	@mkdir -p $(RESULT_DIR)
	@./$(EXPERIMENT_BIN) | tee $(RESULT_DIR)/modes_experiments.txt

benchmark: $(BENCH_BIN)
	@mkdir -p $(RESULT_DIR)
	@./$(BENCH_BIN) --csv $(RESULT_DIR)/bruteforce.csv

clean:
	$(RM) -r $(BUILD_DIR)

help:
	@echo "Available targets:"
	@echo "  all          Builds every binary (default)."
	@echo "  test         Builds and runs both test suites."
	@echo "  examples     Builds and runs the demo program."
	@echo "  experiments  Runs the mode experiments and saves their output."
	@echo "  benchmark    Builds and runs the brute-force benchmark."
	@echo "  clean        Removes the build/ directory."

-include $(DEPS)
