# Makefile - Educational DES implementation in C.
#
# Targets:
#   make            Builds the demo program (default).
#   make examples   Builds and runs the demo program.
#   make clean      Removes all generated artifacts.
#
# Everything generated lives under build/, so `make clean` never touches
# source files and the working tree stays clean.

CC       ?= cc
CFLAGS   ?= -std=c11 -O2 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-prototypes
CPPFLAGS += -Iinclude -MMD -MP
LDFLAGS  ?=

BUILD_DIR := build
OBJ_DIR   := $(BUILD_DIR)/obj
BIN_DIR   := $(BUILD_DIR)/bin

# Core algorithm sources. Listed explicitly rather than with a wildcard:
# src/des_modes.c has no implementation yet, and an empty translation unit is
# an error under -Wpedantic. It will be added here once the first mode lands.
LIB_SRCS := \
	src/des_tables.c \
	src/des_keyschedule.c \
	src/des_feistel.c \
	src/des.c

EXAMPLE_SRCS := examples/main.c

LIB_OBJS     := $(LIB_SRCS:%.c=$(OBJ_DIR)/%.o)
EXAMPLE_OBJS := $(EXAMPLE_SRCS:%.c=$(OBJ_DIR)/%.o)

EXAMPLE_BIN := $(BIN_DIR)/des_demo

# .d files generated by -MMD: they make a header change force recompilation
# of every .c that includes it.
DEPS := $(LIB_OBJS:.o=.d) $(EXAMPLE_OBJS:.o=.d)

.PHONY: all examples clean help

all: $(EXAMPLE_BIN)

$(EXAMPLE_BIN): $(LIB_OBJS) $(EXAMPLE_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(OBJ_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

examples: $(EXAMPLE_BIN)
	@./$(EXAMPLE_BIN)

clean:
	$(RM) -r $(BUILD_DIR)

help:
	@echo "Available targets:"
	@echo "  all       Builds the demo program (default)."
	@echo "  examples  Builds and runs the demo program."
	@echo "  clean     Removes the build/ directory."

-include $(DEPS)
